name: cudaRAHT
channels:
dependencies:
    - python=3.9
    - numba
    - cudatoolkit
    - numpy
    - matplotlib
    - tqdm
    - pip
    - pip:
        - "--editable=git+https://github.com/LTTM/PCutils.git@v0.3.0#egg=PCutils"
